export const EDGES = {
    BASE: 0,
    NUMERIC: 1,
    VEC2: 2,
    VEC3: 3,
    VEC4: 4,
    ENTITY: 5,
    FIRE: 6,
};

export const NODES = {
    START: 0,
    INTERVAL: 1,
    TRANSLATION: 2,
    SCALE: 3,
    ROTATION: 4,
    TRANSLATE: 5,
    RESIZE: 6,
    ROTATE: 7,
    VISIBILITY: 8,
    PLAYER_CONTROLLER: 9,
    DELAY: 10,
    GRAPH_TRANSMITTER: 11,
    GRAPH_RECEIVER: 12,
    BIRD_CONTROLLER: 13,
    COLLISION_START: 14,
    TRIGGER_ENTER: 15,
    SPAWN: 16,
    KEY_PRESS: 17,
    KEY_RELEASE: 18,
    RAY_CAST: 19,
    SELF: 20,
    HAS_TAGS: 21,
    DESTROY: 22,
};